// <auto-generated />
using System;
using DbAuditWithEF.ByEF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DbAuditWithEF.ByEF.Migrations
{
    [DbContext(typeof(ByEFContext))]
    [Migration("20241013123822_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DbAuditWithEF.ByEF.ByEFProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("DbAuditWithEF.ByEF.ByEFProduct", b =>
                {
                    b.OwnsOne("DbAuditWithEF.ByEF.Audit", "Audit", b1 =>
                        {
                            b1.Property<int>("ByEFProductId")
                                .HasColumnType("int");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("CreatedBy");

                            b1.Property<DateTime>("CreatedOn")
                                .HasColumnType("datetime2")
                                .HasColumnName("CreatedOn");

                            b1.Property<string>("ModifiedBy")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("ModifiedBy");

                            b1.Property<DateTime?>("ModifiedOn")
                                .HasColumnType("datetime2")
                                .HasColumnName("ModifiedOn");

                            b1.HasKey("ByEFProductId");

                            b1.ToTable("Products");

                            b1.WithOwner()
                                .HasForeignKey("ByEFProductId");
                        });

                    b.Navigation("Audit")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
